backend:
  name: github
  branch: master
  repo: exshak/portfolio

media_folder: static/images
public_folder: /images

collections:
  - label: Projects
    name: projects
    folder: src/projects
    create: true
    fields:
      - { label: Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Stack, name: stack, widget: string }
      - { label: Link, name: link, widget: string }
      - { label: Repo, name: repo, widget: string }
      - { label: Featured Image, name: featuredImage, widget: image }
      - {
          label: Gallery Images,
          name: galleryImages,
          widget: list,
          required: false,
          field: { label: Gallery Image, name: galleryImage, widget: image },
        }
